import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTypescript from "eslint-config-next/typescript"

export default defineConfig([
  ...nextVitals,
  ...nextTypescript,
  globalIgnores([
    ".next/**",
    ".claude/worktrees/**",
    ".omo/evidence/**",
    "artifacts/**",
    // Vendored MapLibre worker bundle, generated by
    // scripts/copy-maplibre-worker.mjs. Not our source.
    "public/maplibre/**",
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    ".claude/skills/**",
    ".github/skills/**",
    ".opencode/skills/**"
  ])
])
