export type ManeuverKind =
  | "straight"
  | "continue"
  | "depart"
  | "slight-left"
  | "slight-right"
  | "left"
  | "right"
  | "sharp-left"
  | "sharp-right"
  | "keep-left"
  | "keep-right"
  | "merge-left"
  | "merge-right"
  | "fork-left"
  | "fork-right"
  | "ramp-left"
  | "ramp-right"
  | "uturn-left"
  | "uturn-right"
  | "roundabout"
  | "roundabout-enter"
  | "roundabout-exit"
  | "elevator"
  | "ferry"
  | "arrive"
  | "arrive-via"
  | "finish"

export function maneuverKind(sign: number): ManeuverKind {
  if (sign === 4) return "finish"
  if (sign === 5) return "arrive-via"
  if (sign === 6) return "roundabout"
  if (sign === -7) return "slight-left"
  if (sign === 7) return "slight-right"
  if (sign === -3) return "keep-left"
  if (sign === 3) return "keep-right"
  if (sign === -2) return "merge-left"
  if (sign === 2) return "merge-right"
  if (sign === -1) return "fork-left"
  if (sign === 1) return "fork-right"
  if (sign === -98) return "sharp-left"
  if (sign === 98) return "sharp-right"
  if (sign === -8) return "left"
  if (sign === 8) return "right"
  if (sign < 0) return "left"
  if (sign > 0) return "right"
  return "straight"
}
